[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
board_build.mcu = esp32c3
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^2.3.0
    ESP Async WebServer
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
extra_scripts = pre:load_env.py
