[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
board_build.mcu = esp32c3
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^2.3.0
    ESP Async WebServer
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
extra_scripts = pre:load_env.py

; OTA upload - use with: pio run -t upload -e ota
[env:ota]
extends = env:esp32c3
upload_protocol = espota
upload_port = cadence.local
